import type { CanvasCard } from "@/models/trip";
import { getLandingPreviewHotelCardCues } from "./landingPreviewDemoCues";
import { previewId } from "./previewId";

export type KanbanPreviewColumn = {
  label: string;
  dotClass: string;
  cardCount: string;
  cards: CanvasCard[];
};

const landingPreviewHotelCues = getLandingPreviewHotelCardCues();

export const kanbanColumns: KanbanPreviewColumn[] = [
  {
    label: "Day 1 — Arrival",
    dotClass: "bg-amber-500",
    cardCount: "3 cards",
    cards: [
      {
        id: previewId("flight"),
        type: "flight",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Flight",
        subtitle: "Dec 14 · Departs 11:05am · 12h 40m nonstop",
        tag: "Day 1 · Arrival",
        tagColor: "amber",
        price: "$743",
        day: 1,
      },
      {
        id: previewId("ryokan"),
        type: "hotel",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Hiiragiya Ryokan",
        subtitle: landingPreviewHotelCues.subtitle,
        image: "/images/ryokan.jpg",
        tag: landingPreviewHotelCues.tag,
        tagColor: landingPreviewHotelCues.tagColor,
        day: 1,
      },
      {
        id: previewId("pack-light"),
        type: "sticky",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Pack light!",
        subtitle: "Ryokan provides yukata & toiletries. Just bring camera + layers.",
        color: "#fef3c7",
        day: 1,
      },
    ],
  },
  {
    label: "Day 2 — Fushimi Inari + Gion",
    dotClass: "bg-primary",
    cardCount: "3 cards",
    cards: [
      {
        id: previewId("fushimi"),
        type: "polaroid",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Fushimi Inari",
        subtitle: "Go at 5am — Yuki",
        image: "/images/fushimi-inari.jpg",
        tag: "Day 2",
        tagColor: "orange",
        day: 2,
      },
      {
        id: previewId("yuki"),
        type: "sticky",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Yuki says:",
        subtitle: '"Go at 5am!! The light through the torii is incredible and zero tourists 🌅"',
        color: "#fef3c7",
        day: 2,
      },
      {
        id: previewId("nishiki"),
        type: "article",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Nishiki Market",
        subtitle: "Kyoto's kitchen — street food heaven",
        image: "/images/nishiki-market.jpg",
        tag: "Day 2",
        tagColor: "orange",
        day: 2,
      },
    ],
  },
  {
    label: "Day 3 — Arashiyama",
    dotClass: "bg-emerald-500",
    cardCount: "3 cards",
    cards: [
      {
        id: previewId("arashiyama"),
        type: "polaroid",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Arashiyama Bamboo",
        subtitle: "Early morning walk",
        image: "/images/arashiyama.jpg",
        tag: "Day 3",
        tagColor: "orange",
        day: 3,
      },
      {
        id: previewId("jr-pass"),
        type: "sticky",
        x: 0,
        y: 0,
        rotation: 0,
        title: "JR Pass ✓",
        subtitle: "Arashiyama is covered! Take the Sagano Scenic Railway.",
        color: "#d1fae5",
        day: 3,
      },
      {
        id: previewId("tenryu"),
        type: "article",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Tenryu-ji Garden",
        subtitle: "UNESCO World Heritage · Zen garden with Arashiyama mountain backdrop",
        tag: "Day 3 · Must-see",
        tagColor: "orange",
        day: 3,
      },
    ],
  },
  {
    label: "Day 4 — Gion + Logistics",
    dotClass: "bg-rose-500",
    cardCount: "4 cards",
    cards: [
      {
        id: previewId("gion"),
        type: "polaroid",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Gion at Dusk",
        subtitle: "Traditional machiya district",
        image: "/images/gion.jpg",
        tag: "Day 4",
        tagColor: "orange",
        day: 4,
      },
      {
        id: previewId("dinner"),
        type: "sticky",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Dinner: Junsei",
        subtitle: "Tofu kaiseki near Nanzenji. Book 2 weeks ahead!",
        color: "#ffe4e6",
        day: 4,
      },
      {
        id: previewId("wifi"),
        type: "note",
        x: 0,
        y: 0,
        rotation: 0,
        title: "Pocket WiFi",
        subtitle: "Pick up at KIX airport · ¥600/day · Pre-book online",
        day: 4,
      },
    ],
  },
];
